Add LibPSTerra to AlpsLib, implement API-Connection
AlpsBTE/Alps-Lib pull request #1
Opened 2024-02-18 22:34 UTC by GrJo

As planned with the BTE BuildTeamsTools developers, this moves most of the code from AlpsLib/PlotSystemTerra into the AlpsLib Library, so that it can be used from plugins with minimal code. The corresponding change to PlotSystemTerra is also ready to be pulled back from this fork to main - i will prepare the pull-request as well. 

I have created a new submodule "LibPSTerra" in AlpsLib for that, and bumped the version numbers to 1.1.0 across the board for this change.

Also, this change finally implements the **Datamode "API"** by adding an appropriate interface `Connection` thats implemented by `DatabaseConnection `(thats where the database query code has moved to) and `NetworkAPIConnection` (the new code thats using the [API](https://buildtheearth.github.io/network-api/). Along the way, i added some classes to represent/group the data thats returned by the database/network queries (`Server.java, Plot.java, Country.java`)

Everything has been tested as far as I could, i also added some unit-tests/integration tests in the package test/java/TestConnections.java

2024-02-25 18:00 UTC, LordTuxn requested changes
lgtm, please implement the requested changes to avoid duplicate code.

2024-02-25 20:05 UTC, GrJo commented on libpsterra/src/main/java/com/alpsbte/alpslib/libpsterra/utils/ItemBuilder.java
the Itembuilder from AlpsLib/utils does not work in 1.12 (AdventureAPI). I moved the Itembuilder from libpsterra there and renamed it LegacyItembuilder.
[12e472d](https://github.com/AlpsBTE/Alps-Lib/pull/1/commits/12e472d182575b37b5a1c8e6ddb0858274cdb50a)
[fe6fc5a](https://github.com/AlpsBTE/Alps-Lib/pull/1/commits/fe6fc5aeeddc8cd6afe2e94fba337276a602a231)

2024-02-25 20:06 UTC, GrJo commented on libpsterra/src/main/java/com/alpsbte/alpslib/libpsterra/utils/LoreBuilder.java
done
[fe6fc5a](https://github.com/AlpsBTE/Alps-Lib/pull/1/commits/fe6fc5aeeddc8cd6afe2e94fba337276a602a231)

2024-02-25 20:08 UTC, GrJo commented on libpsterra/src/main/java/com/alpsbte/alpslib/libpsterra/utils/Updater.java
> +        Bukkit.getConsoleSender().sendMessage("§c[BuildTeam Plugin] §eThe server automatically installed a new update (v" + newVersion + ").");
I did not touch that code. Thats as-is in the current Plot-System-Terra plugin... 
https://github.com/AlpsBTE/Plot-System-Terra/blob/b365228b887fdb26ea1d1a59994e202d6d9a1605/src/main/java/com/alpsbte/plotsystemterra/utils/Updater.java#L120

2024-02-25 20:17 UTC, GrJo commented on libpsterra/src/main/java/com/alpsbte/alpslib/libpsterra/utils/Utils.java
> +    public static ItemStack getItemHead(String headID) {
using AlpsLib/utils for Head-Query - done
[a3191e0](https://github.com/AlpsBTE/Alps-Lib/pull/1/commits/a3191e08bd188d8c5286b0697178133ca8a185af)

2024-02-25 20:23 UTC, GrJo commented on libpsterra/src/main/java/com/alpsbte/alpslib/libpsterra/utils/Utils.java
> +    public static Integer tryParseInt(String integer) {
well spotted. removed the code duplicate.
[72258b5](https://github.com/AlpsBTE/Alps-Lib/pull/1/commits/72258b5c98e3f13b0d12bcf66923f27766c4979f)

2024-02-25 20:48 UTC, GrJo commented on libpsterra/src/main/java/com/alpsbte/alpslib/libpsterra/core/config/ConfigNotImplementedException.java
removed the duplicated file
[7466df7](https://github.com/AlpsBTE/Alps-Lib/pull/1/commits/7466df7a2712009c51f42e68e3a5e782c5f6aacb)

2024-02-25 20:49 UTC, GrJo commented
@LordTuxn: can we skip the rest of the Config-Handling for now? I have removed the Exception-Duplicate. But the rest of the config handling is sufficiently different that i dont want to touch this right now.

2024-03-03 20:56 UTC, LordTuxn commented
> @LordTuxn: can we skip the rest of the Config-Handling for now? I have removed the Exception-Duplicate. But the rest of the config handling is sufficiently different that i dont want to touch this right now.

Yeah sure, it's not that important as long as it works.

2024-03-03 20:57 UTC, LordTuxn approved these changes

2024-03-03 20:57 UTC, merged